# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0003_auto_20170104_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('datefrom', models.DateTimeField(null=True)),
                ('deteuntil', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.User')),
                ('userlist', models.ManyToManyField(related_name='userlist', to='login_app.User')),
            ],
        ),
    ]
