# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20170104_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='datefrom',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dateuntil',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
